### PR TITLE
fix for large frame/package pts values.

### LINKED ISSUE #116: time out will not stop playing
Hi @lukasf 
When playing some videos, the end of time does not stop and the time continues to increase.
Here is the sample file:
https://www.dropbox.com/s/6r8r1zh382rx3cc/2Pac%20-%20Pac%27s%20Life%20Ft.%20T.I.%2C%20Ashanti.vob?dl=0

### PR DESCRIPTION
**Pull request by mcosmin222**
This fixes #116 

@lukasf 
The problem seem to be caused by 
framePts  =  avFrame->best_effort_timestamp;
You were right, we did miss a check against AV_NOPTS_VALUE there.
That weird number was actually AV_NOPTS_VALUE but signed. 

I also added a few extra checks on frame/ package pts upstream. This should handle some more possible edge cases.

### CODE REVIEW

File: FFmpegInterop/UncompressedSampleProvider.cpp [hunk 1]
```diff
@@ -113,17 +113,18 @@ HRESULT UncompressedSampleProvider::GetFrameFromFFmpegDecoder(AVFrame* avFrame,
 		else
 		{
 			// Update the timestamp
-			if (avFrame->pts != AV_NOPTS_VALUE)
+			if (avFrame->pts != AV_NOPTS_VALUE && avFrame->pts >= 0 && avFrame->pts - nextFramePts < 600000000)
```
Comment (lukasf) [inline FFmpegInterop/UncompressedSampleProvider.cpp]: I am not 100% sure if negative pts values are always an error. Adding this >= 0 check here might introduce new problems with files out in the field. Since the problem was caused by a bug on our side, I would propose to not add >= 0 check here. For the second check, it should be changed to: (!hasNextFramePts ||  avFrame->pts - nextFramePts < 600000000). E.g. after a seek, we do not have a valid nextFramePts, so the check could cause problems on file seeks (only on files with very long durations though).

File: FFmpegInterop/MediaSampleProvider.cpp [hunk 2]
```diff
@@ -228,7 +228,7 @@ HRESULT MediaSampleProvider::GetNextPacket(AVPacket** avPacket, LONGLONG & packe
 		*avPacket = packet;
 
 		packetDuration = packet->duration;
-		if (packet->pts != AV_NOPTS_VALUE)
+		if (packet->pts != AV_NOPTS_VALUE && packet->pts >= 0 && packet->pts - m_nextPacketPts < 600000000)
```
Comment (lukasf) [inline FFmpegInterop/MediaSampleProvider.cpp]: Remove pts >= 0 check (same reason as in UncompressedSampleProvider comment).

And then I thing I have spotted a problem in MediaSampleProvider (not related to your change): The m_nextPacketPts never gets reset on a seek operation. After a seek, the m_nextPacketPts will stay on the same value as before, so we might use wrong pts values if packets after seek do not contain a pts value on their own. To fix this, we'd need to update m_nextPacketPts with the seek target position (taking into account). It probably only ever affects broken files, still, I think we should fix this. It might improve seeking in partly broken files. This does not need to be fixed in this PR, we can do a separate PR for that.

**Comment by mcosmin222** [comment]
Hi @lukasf 
I removed the checks and replaced as you suggested.
